### ISSUE TITLE
Cannot establish a connection remotely using pbm client 0.2.2

### ISSUE THREAD

**Issue by mrrd** [petabridge/petabridge.cmd-issues#19]
We are having a strange issue which only shows itself remotely.

We have a cluster which is currently running akka 1.2.3 and pbm host/client 0.2.2 on several of the machines, when connecting locally on the machine in question with pbm host on it using the pbm client all is fine and works as expected.

But remotely the pbm client hangs indefinitely and does not get any further than the copyright message line, it does not do what it does locally return the next line that starts "successfully connected to [", it also does not return a connection failed message either (which I have seen when accidentally entering an incorrect ip/port).

I was wondering if this is an issue anyone else has experienced and if upgrading to akka 1.3.1 and the associated packages like the latest pbm will resolve this for us, we would like confirmation on this so we can then escalate the priority of our planned upgrade to 1.3.1.

If you need any extra info let me know.

**Comment by Aaronontheweb** [comment]
Thanks @mrrd! Subscribe to this issue and we'll post updates here as we look into this.

**Comment by mithril52** [comment]
I as well have been having tis issue using 1.2.3 Akka and 0.2.2 pbm. Works everytime locally, but remotely, it almost always takes several attempts to connect successfully, sometimes upwards of 20-30 attempts.

**Comment by Aaronontheweb** [comment]
@mithril52 wow, that's bizarre... we're not really doing too much crazy stuff other than just opening a basic TCP connection using Akka.IO. That part of Akka.NET was significantly re-written in Akka.NET v1.3.1 (which Petabridge.Cmd v0.3.0 uses) but still the connectivity part should not be affected.

I'll look into adding some automatic retry capability in the connectivity layer on the client as a first-step measure.
