### ISSUE TITLE
serialization error: Destination array is not long enough

### ISSUE THREAD

**Issue by pmbanka** [petabridge/petabridge.cmd-issues#21]
I just installed and tried out Petabridge cmd on our system. When running 

`pbm host:port actor hierarchy > result.txt`

the result file has some actors (163 of them) and the final line in the file reads

`serialization error: Destination array is not long enough to copy all the items in the collection. Check array index and length.`

Maybe related to https://github.com/petabridge/petabridge.cmd-issues/issues/17

 pbm 0.3.1.0

**Comment by Aaronontheweb** [comment]
Roughly how large is the destination actor hierarchy?

**Comment by pmbanka** [comment]
Great question, that's what I'm trying to find out. @object any insight?

**Comment by object** [comment]
I believe our total hierarchy consists of a few hundred actors, not thousands. So it's relatively decent number.

**Comment by Aaronontheweb** [comment]
Ok, so this is probably a fairly common use case. Got it. I'll dig into this in more detailed. Do you have a copy of the full error message? Wonder if it's an issue with the way we're using Protobuf.

**Comment by pmbanka** [comment]
The message I included in the first post is everything I got. I don't see any stack traces related to that in our logs, which is weird :/

**Comment by nvivo** [comment]
Hi, any news on this issue?

**Comment by 4deeptech** [comment]
I get this same message doing "cluster show".  It lists 4 nodes and then error...

**Comment by Aaronontheweb** [comment]
Hi folks,

We're on this - have an issue open and am working on reproducing it.

**Comment by pmbanka** [comment]
FWIW, I also noticed this issue happening when running `cluster show` command. Our cluster has only 6 nodes.

**Comment by Aaronontheweb** [comment]
Found the issue; it's this, inside Akka.IO: https://github.com/akkadotnet/akka.net/issues/3183

**Comment by Aaronontheweb** [comment]
Going to patch that issue as part of the 1.3.3 release.

**Comment by Aaronontheweb** [comment]
Have this fixed! Going to be releasing a v0.3.2 tonight.

**Comment by Aaronontheweb** [comment]
Turns it out wasn't an Akka.IO issue; bug with our serializer not handling some rare but not impossible edge cases involving really, really short frames received from the socket.

**Comment by Aaronontheweb** [comment]
Petabridge.Cmd v0.3.2 is now live on Chocolatey and NuGet.org. Official announcement will be out tomorrow am. Sorry for the delay on this - wrote a pretty heavy-duty set of model-based tests aimed at nailing this one.
