### ISSUE TITLE
Modify cluster leave command to support having multiple nodes leave at once

### ISSUE THREAD

**Issue by Aaronontheweb** [petabridge/petabridge.cmd-issues#28]
Should be able to support `cluster leave -a [addr1] -a [addr2]` - currently can only support one node address at a time.

**Comment by Aaronontheweb** [comment]
@IgorFedchenko I believe we already support this, but I'm not 100% sure - might be as simple as firing up a test cluster and seeing if the `pbm cluster leave` command supports multiple `-a` parameters.

**Comment by IgorFedchenko** [comment]
@Aaronontheweb Nope, this is not supported right now:
```
cluster leave -a localhost:8081 -a localhost:8082
ERR: could not execute command
Saw more than 1 value for argument [address] for command [cluster leave], which is not allowed for [address].
```

And this is explicitly disabled with `AllowMultiple(false)` in the source code, so I will need to check if allowing multiple parameters will break anything.

**Comment by IgorFedchenko** [comment]
Actually, internal command handling seems to be supporting that - it is assuming that multiple switches could be given. I will need to test if this works with `AllowMultiple(true)` setting.

UPDATE: nope, it is doing `SingleOrDefault` to make sure it is handling only one Leave at a time. I will need to learn more about possible reasons then.

**Comment by IgorFedchenko** [comment]
Ok, so as discussed in chat, there is no strong reason to not allow multiple addresses to be specified here. I will make a PR soon.
