### ISSUE TITLE
My system time and logging output time are not the same.

### ISSUE THREAD

**Issue by jiyeongj** [petabridge/petabridge.cmd-issues#31]
Hello :)

My system time and logging output time are not the same.
Maybe it's because of the standard time. My country's standard time is (GMT+9).
Is there a way to set this up?

![image](https://user-images.githubusercontent.com/45417052/70398587-644a6080-1a60-11ea-8012-48184981e598.png)

**Comment by Aaronontheweb** [comment]
@jiyeongj I think this is an Akka.NET issue - we don't localize timezones at all in the logging system there. It's all done in UTC: https://github.com/akkadotnet/akka.net/blob/51ed45fbcef31c6012e5ffe612e9b0a4b9367fba/src/core/Akka/Event/LogEvent.cs#L51

**Comment by Aaronontheweb** [comment]
I'm going to close this issue here, but if you feel strongly that this should be added to Akka.NET I'd recommend that you open an issue on the main repository there.
