### ISSUE TITLE
Result address of 'cluster-sharding region-stats'

### ISSUE THREAD

**Issue by jiyeongj** [petabridge/petabridge.cmd-issues#32]
Hello!

- Akka.Cluster.Sharding version : 1.4.0-beta3
- Petabridge.Cmd.Cluster.Sharding version : 0.7.0-beta
- This issue's github repo : https://github.com/jiyeongj/Issue/tree/master/AkkaClusterSharding_Cmd

1. SeedNode1  HOCON

   ```
	remote {
		dot-netty.tcp {
			hostname = "localhost"
			port = 8081
		}
	}
   ```
1. SeedNode2 HOCON

   ```
	remote {
		dot-netty.tcp {
			hostname = "localhost"
			port = 8082
		}
	}
   ```
1. Run the `SeedNode1`, `SeedNode2`
1. The results of `cluster-sharding local-stats` and `cluster-sharding region-stats` are as follows.

![image](https://user-images.githubusercontent.com/45417052/71339508-0f960200-2597-11ea-812b-47d13222254b.png)

Both addresses were printed at 8081.
I think the second address should be printed at 8082.
This seems like a bug. right?

**Comment by IgorFedchenko** [comment]
I was able to get same error using reproduction repository (thank you for that @jiyeongj !):
![image](https://user-images.githubusercontent.com/9683660/97578668-2b153900-1a02-11eb-80f4-e71973b5ea1e.png)

But after upgrading `Petabridge.Cmd.*` packages to `0.8.0`, all is working properly:
![image](https://user-images.githubusercontent.com/9683660/97564095-1a11fb00-19f5-11eb-9e12-73bfb0c5c1f5.png)

So upgrading to the latest version fixes the issue.
