### ISSUE TITLE
Exit code is 0 when failed to connect

### ISSUE THREAD

**Issue by ia64mail** [petabridge/petabridge.cmd-issues#33]
Hello, 

We use `pbm` client for container liveness check in the K8s deployment. Apparently, it always return exit code 0 even if couldn't connect to the host.

```
C:\>pbm 127.0.0.1:9110 cluster status
Failed to connect to 127.0.0.1:9110 within 00:00:05

C:\>echo %ERRORLEVEL%
0
```
pbm client version - 0.8.0
Microsoft Windows [Version 10.0.17763.1282]

**Comment by Aaronontheweb** [comment]
This is definitely a bug - one of the members of our team is working on a fix for it now. Added to the v0.8.1 milestone.

**Comment by IgorFedchenko** [comment]
Fixed with PR attached
