### ISSUE TITLE
Manual download link was broken

### ISSUE THREAD

**Issue by seungyongshim** [petabridge/petabridge.cmd-issues#39]
- https://cmd.petabridge.com/articles/install/downloads.html
- Latest download link was broken
- v0.8.0 | 03-11-2020 | Download

**Comment by IgorFedchenko** [comment]
Hi @seungyongshim - thanks, we will fix this ASAP. 

In the meanwhile - feel free to use this link to download the latest `0.8.2` package version: https://petabridgecmd.blob.core.windows.net/petabridge-cmd/petabridge-cmd/Petabridge.Cmd.Client.0.8.2.zip

**Comment by Aaronontheweb** [comment]
Whoops - looks like I goofed on that area of the website. We'll fix that today.

**Comment by Aaronontheweb** [comment]
This is now fixed.
