### ISSUE TITLE
version 0.8.3 - .net 5 support

### ISSUE THREAD

**Issue by mdupras** [petabridge/petabridge.cmd-issues#42]
According to the [Release note](https://cmd.petabridge.com/articles/RELEASE_NOTES.html) support for .NET 5 as been added.

But if I try to run it on a machine that only have .net 5 install it doesn't work.

![image](https://user-images.githubusercontent.com/2389799/116594578-5f55ad80-a8f0-11eb-9b63-a072fc371d3a.png)

**Comment by Arkatufus** [comment]
We've just added .NET 5.0 support on the new v0.8.4 release, can you give it another try?

**Comment by mdupras** [comment]
Yes version 0.8.4 works perfectly.
Thank you!
