### ISSUE TITLE
Displaying full semantic version of cluster nodes

### ISSUE THREAD

**Issue by object** [petabridge/petabridge.cmd-issues#44]
We recently switched to SemVer for our Akka-based services, so now we use 3 first versions number for major/minor/patch version, followed by the number of commits since the last patch, e.g.:

2.6.1.4 (AssemblyVersion and AssemblyFileVersion)
2.6.1-4+b5837ab (AssemblyInformationalVersion)

Petabridge CMD shows only 3 first numbers, so it only shows 2.6.1. This becomes inconvenient when we frequently update services after newer commits and can't see what commit number is installed.

Are there any specific reasons why Petabridge CMD only show 3 first version parts, and not the full version information?

@Aaronontheweb

**Comment by Aaronontheweb** [comment]
@object that might actually be an Akka.NET issue with how `AppVersion` is implemented, since all we do in Petabridge.Cmd is print it out: https://github.com/akkadotnet/akka.net/blob/21762b90ac1d7db670487dda1368d84c61d693e5/src/core/Akka/Util/AppVersion.cs

**Comment by Aaronontheweb** [comment]
This is what our Petabridge.Cmd string formatting code for cluster members looks like:

```csharp
public static string ToPrettyPrint(this Member m, bool isUnreachable)
{
    return
        $"{m.Address} | [{string.Join(",", m.Roles)}] | {m.Status.ToPrettyPrint()} | {Reachability(isUnreachable)} | {m.AppVersion}";
}
```

**Comment by object** [comment]
Ah I see, thanks for finding it out. I will look into AppVersion.
