### ISSUE TITLE
Wrong installation script.

### ISSUE THREAD

**Issue by powerumc** [petabridge/petabridge.cmd-issues#47]
Link: https://cmd.petabridge.com/articles/quickstart.html

The following script is wrong.
```
Setup
To get started, install the pbm client as a .NET Core global tool.

> dotnet install -g pbm
```

It should be the following script.
<del>`dotnet install -g pbm`</del> -> `dotnet tool install -g pbm`

**Comment by Aaronontheweb** [comment]
Whoops, thanks for reporting this - looks like we fixed it a while ago.
