### ISSUE TITLE
Download methods for PBM

### ISSUE THREAD

**Issue by xas** [petabridge/petabridge.cmd-issues#49]
The v0.8.5 is the last version of PBM available in chocolatey or for a manual download (blob not found).

Are these methods now obsolete or just some missing links update ?

**Comment by Aaronontheweb** [comment]
That's a good question about Chocolatey - we still deploy to it each time we do a release. I wonder if we're being hung up in the approval pipeline there.

However, there is an easier way to install `pbm` now via the `dotnet tools` CLI: https://cmd.petabridge.com/articles/install/index.html#client-installation-via-net-core-global-tools

## Install

```shell
dotnet tool install --global pbm 
```

## Upgrade

```shell
dotnet tool update -g pbm
```

I'll see what's going on with Chocolatey and why none of our recent updates have made it there. It also looks like our manual downloads have stopped working too... This must be a build system issue.

**Comment by Aaronontheweb** [comment]
Bah, even with Petabridge.Cmd 1.2.0 Azure Blob uploads still aren't working - going to need to look into this more. We determined that this was an issue with an update to our build system (moved off the old WSYWIG Azure Pipeline to YAML).

**Comment by Aaronontheweb** [comment]
This has been fixed as of Petabridge.Cmd 1.2.1
