### ISSUE TITLE
Command History - Left Arrow moves cursor right

### ISSUE THREAD

**Issue by alanschrank** [petabridge/petabridge.cmd-issues#6]
v0.2.1
In trying to edit a command from the command history to insert information earlier in the command for re-execution;
* up arrow to get old command
* left arrow moves cursor right instead of left
* Backspace does move cursor left but erases characters that are not retrieved by right arrow

**Comment by Aaronontheweb** [comment]
@alanschrank 

> left arrow moves cursor right instead of left

Can I blame that one on my dyslexia? ;)

Good catch. Can reproduce - will see if we can fix this in a new point release.

**Comment by Aaronontheweb** [comment]
Resolved - will be going live in v0.2.2
